# yaml-language-server: $schema=https://render.com/schema/render.yaml.json
services:
  - type: web
    runtime: docker
    name: knot
    region: ohio
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: LOG_LEVEL
        value: info
      - key: DATABASE_URL
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: SLACK_BOT_TOKEN
        sync: false
